@host = http://localhost:8080

###
get {{host}}/api/pokemon

###
post {{host}}/api/pokemon
Content-Type: application/json

 {
    "idpokemon": 11,
    "name": "pookemon 5",
    "status": "A",
    "category": {
      "idcategory": 1,
      "name": "fuego"
    }
    }